[platformio]
default_envs = s3_master

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BNO08x
    adafruit/Adafruit DRV2605 Library

[env:c3_node]
board = seeed_xiao_esp32c3
build_src_filter = -<*> +<main_c3.cpp>

[env:s3_master]
board = seeed_xiao_esp32s3
build_src_filter = -<*> +<main_s3.cpp>